# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Dec 17 17:24:17 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(791, 557)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 252, 241);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.infoWidget = QtGui.QTabWidget(self.centralwidget)
        self.infoWidget.setGeometry(QtCore.QRect(10, 80, 201, 461))
        self.infoWidget.setObjectName(_fromUtf8("infoWidget"))
        self.tabMessages = QtGui.QWidget()
        self.tabMessages.setObjectName(_fromUtf8("tabMessages"))
        self.messageBrowser = QtGui.QTextBrowser(self.tabMessages)
        self.messageBrowser.setGeometry(QtCore.QRect(7, 0, 181, 431))
        self.messageBrowser.setObjectName(_fromUtf8("messageBrowser"))
        self.infoWidget.addTab(self.tabMessages, _fromUtf8(""))
        self.tabScores = QtGui.QWidget()
        self.tabScores.setObjectName(_fromUtf8("tabScores"))
        self.scoreBrowser = QtGui.QTextBrowser(self.tabScores)
        self.scoreBrowser.setGeometry(QtCore.QRect(7, 0, 181, 431))
        self.scoreBrowser.setObjectName(_fromUtf8("scoreBrowser"))
        self.infoWidget.addTab(self.tabScores, _fromUtf8(""))
        self.hallWidget = QtGui.QTabWidget(self.centralwidget)
        self.hallWidget.setGeometry(QtCore.QRect(220, 80, 551, 411))
        self.hallWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.hallWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hallWidget.setAutoFillBackground(False)
        self.hallWidget.setStyleSheet(_fromUtf8("border-color: rgb(225, 121, 25);\n"
"background-color: rgb(255, 255, 248);"))
        self.hallWidget.setTabPosition(QtGui.QTabWidget.North)
        self.hallWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.hallWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.hallWidget.setObjectName(_fromUtf8("hallWidget"))
        self.tabHall1 = QtGui.QWidget()
        self.tabHall1.setEnabled(True)
        self.tabHall1.setStyleSheet(_fromUtf8("background-color: rgb(255, 229, 202);"))
        self.tabHall1.setObjectName(_fromUtf8("tabHall1"))
        self.desk1 = QtGui.QGroupBox(self.tabHall1)
        self.desk1.setGeometry(QtCore.QRect(40, 10, 191, 141))
        self.desk1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.desk1.setFlat(False)
        self.desk1.setObjectName(_fromUtf8("desk1"))
        self.btnLeft1 = QtGui.QPushButton(self.desk1)
        self.btnLeft1.setGeometry(QtCore.QRect(10, 40, 50, 50))
        self.btnLeft1.setText(_fromUtf8(""))
        self.btnLeft1.setObjectName(_fromUtf8("btnLeft1"))
        self.btnRight1 = QtGui.QPushButton(self.desk1)
        self.btnRight1.setGeometry(QtCore.QRect(130, 40, 50, 50))
        self.btnRight1.setText(_fromUtf8(""))
        self.btnRight1.setObjectName(_fromUtf8("btnRight1"))
        self.widget = QtGui.QWidget(self.desk1)
        self.widget.setGeometry(QtCore.QRect(70, 40, 55, 55))
        self.widget.setStyleSheet(_fromUtf8("background-color: rgb(159, 238, 255);"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.lblLeft1 = QtGui.QLabel(self.desk1)
        self.lblLeft1.setGeometry(QtCore.QRect(20, 100, 41, 16))
        self.lblLeft1.setObjectName(_fromUtf8("lblLeft1"))
        self.lblRight1 = QtGui.QLabel(self.desk1)
        self.lblRight1.setGeometry(QtCore.QRect(140, 100, 41, 16))
        self.lblRight1.setObjectName(_fromUtf8("lblRight1"))
        self.desk2 = QtGui.QGroupBox(self.tabHall1)
        self.desk2.setGeometry(QtCore.QRect(310, 10, 191, 141))
        self.desk2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.desk2.setFlat(False)
        self.desk2.setObjectName(_fromUtf8("desk2"))
        self.btnLeft2 = QtGui.QPushButton(self.desk2)
        self.btnLeft2.setGeometry(QtCore.QRect(10, 40, 50, 50))
        self.btnLeft2.setText(_fromUtf8(""))
        self.btnLeft2.setObjectName(_fromUtf8("btnLeft2"))
        self.btnRight2 = QtGui.QPushButton(self.desk2)
        self.btnRight2.setGeometry(QtCore.QRect(130, 40, 50, 50))
        self.btnRight2.setText(_fromUtf8(""))
        self.btnRight2.setObjectName(_fromUtf8("btnRight2"))
        self.widget_2 = QtGui.QWidget(self.desk2)
        self.widget_2.setGeometry(QtCore.QRect(70, 40, 55, 55))
        self.widget_2.setStyleSheet(_fromUtf8("background-color: rgb(159, 238, 255);"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.lblLeft2 = QtGui.QLabel(self.desk2)
        self.lblLeft2.setGeometry(QtCore.QRect(20, 100, 41, 16))
        self.lblLeft2.setObjectName(_fromUtf8("lblLeft2"))
        self.lblRight2 = QtGui.QLabel(self.desk2)
        self.lblRight2.setGeometry(QtCore.QRect(140, 100, 41, 16))
        self.lblRight2.setObjectName(_fromUtf8("lblRight2"))
        self.desk3 = QtGui.QGroupBox(self.tabHall1)
        self.desk3.setGeometry(QtCore.QRect(40, 200, 191, 141))
        self.desk3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.desk3.setFlat(False)
        self.desk3.setObjectName(_fromUtf8("desk3"))
        self.btnLeft3 = QtGui.QPushButton(self.desk3)
        self.btnLeft3.setGeometry(QtCore.QRect(10, 40, 50, 50))
        self.btnLeft3.setText(_fromUtf8(""))
        self.btnLeft3.setObjectName(_fromUtf8("btnLeft3"))
        self.btnRight3 = QtGui.QPushButton(self.desk3)
        self.btnRight3.setGeometry(QtCore.QRect(130, 40, 50, 50))
        self.btnRight3.setText(_fromUtf8(""))
        self.btnRight3.setObjectName(_fromUtf8("btnRight3"))
        self.widget_3 = QtGui.QWidget(self.desk3)
        self.widget_3.setGeometry(QtCore.QRect(70, 40, 55, 55))
        self.widget_3.setStyleSheet(_fromUtf8("background-color: rgb(159, 238, 255);"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.lblLeft3 = QtGui.QLabel(self.desk3)
        self.lblLeft3.setGeometry(QtCore.QRect(20, 100, 41, 16))
        self.lblLeft3.setObjectName(_fromUtf8("lblLeft3"))
        self.lblRight3 = QtGui.QLabel(self.desk3)
        self.lblRight3.setGeometry(QtCore.QRect(140, 100, 41, 16))
        self.lblRight3.setObjectName(_fromUtf8("lblRight3"))
        self.desk4 = QtGui.QGroupBox(self.tabHall1)
        self.desk4.setGeometry(QtCore.QRect(310, 200, 191, 141))
        self.desk4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.desk4.setFlat(False)
        self.desk4.setObjectName(_fromUtf8("desk4"))
        self.btnLeft4 = QtGui.QPushButton(self.desk4)
        self.btnLeft4.setGeometry(QtCore.QRect(10, 40, 50, 50))
        self.btnLeft4.setText(_fromUtf8(""))
        self.btnLeft4.setObjectName(_fromUtf8("btnLeft4"))
        self.btnRight4 = QtGui.QPushButton(self.desk4)
        self.btnRight4.setGeometry(QtCore.QRect(130, 40, 50, 50))
        self.btnRight4.setText(_fromUtf8(""))
        self.btnRight4.setObjectName(_fromUtf8("btnRight4"))
        self.widget_4 = QtGui.QWidget(self.desk4)
        self.widget_4.setGeometry(QtCore.QRect(70, 40, 55, 55))
        self.widget_4.setStyleSheet(_fromUtf8("background-color: rgb(159, 238, 255);"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.lblLeft4 = QtGui.QLabel(self.desk4)
        self.lblLeft4.setGeometry(QtCore.QRect(20, 100, 41, 16))
        self.lblLeft4.setObjectName(_fromUtf8("lblLeft4"))
        self.lblRight4 = QtGui.QLabel(self.desk4)
        self.lblRight4.setGeometry(QtCore.QRect(140, 100, 41, 16))
        self.lblRight4.setObjectName(_fromUtf8("lblRight4"))
        self.hallWidget.addTab(self.tabHall1, _fromUtf8(""))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(220, 510, 471, 31))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.btnSend = QtGui.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(700, 510, 71, 32))
        self.btnSend.setObjectName(_fromUtf8("btnSend"))
        self.logoWidget = QtGui.QWidget(self.centralwidget)
        self.logoWidget.setGeometry(QtCore.QRect(10, 20, 201, 51))
        self.logoWidget.setStyleSheet(_fromUtf8("background-color: rgb(207, 255, 214);"))
        self.logoWidget.setObjectName(_fromUtf8("logoWidget"))
        self.avatar = QtGui.QWidget(self.centralwidget)
        self.avatar.setGeometry(QtCore.QRect(630, 28, 51, 51))
        self.avatar.setStyleSheet(_fromUtf8("background-color: rgb(207, 255, 214);"))
        self.avatar.setObjectName(_fromUtf8("avatar"))
        self.lblUsername = QtGui.QLabel(self.centralwidget)
        self.lblUsername.setGeometry(QtCore.QRect(700, 30, 62, 16))
        self.lblUsername.setText(_fromUtf8(""))
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.lblScore = QtGui.QLabel(self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(700, 60, 62, 16))
        self.lblScore.setObjectName(_fromUtf8("lblScore"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.infoWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.infoWidget.setTabText(self.infoWidget.indexOf(self.tabMessages), _translate("MainWindow", "信息", None))
        self.infoWidget.setTabText(self.infoWidget.indexOf(self.tabScores), _translate("MainWindow", "排行榜", None))
        self.desk1.setTitle(_translate("MainWindow", "桌子1", None))
        self.lblLeft1.setText(_translate("MainWindow", "user1", None))
        self.lblRight1.setText(_translate("MainWindow", "user2", None))
        self.desk2.setTitle(_translate("MainWindow", "桌子2", None))
        self.lblLeft2.setText(_translate("MainWindow", "user1", None))
        self.lblRight2.setText(_translate("MainWindow", "user2", None))
        self.desk3.setTitle(_translate("MainWindow", "桌子3", None))
        self.lblLeft3.setText(_translate("MainWindow", "user1", None))
        self.lblRight3.setText(_translate("MainWindow", "user2", None))
        self.desk4.setTitle(_translate("MainWindow", "桌子4", None))
        self.lblLeft4.setText(_translate("MainWindow", "user1", None))
        self.lblRight4.setText(_translate("MainWindow", "user2", None))
        self.hallWidget.setTabText(self.hallWidget.indexOf(self.tabHall1), _translate("MainWindow", "大厅1", None))
        self.btnSend.setText(_translate("MainWindow", "发送", None))
        self.lblScore.setText(_translate("MainWindow", "积分：10", None))

